### ISSUE TITLE
Implement disposition initiator/participant for round robin approach

### ISSUE THREAD

**Issue by OliverStolzBO** [iml130/sola#31]
For comparison to decentralized auction based algorithms, central task assignment should be introduced for the cpps scenario.  

Therefore, the corresponding disposition initiator (the central optimizer) and disposition participants (the AMRs) for round robin as a baseline algorithm should be implemented.

The message types defined in #25 should be used for the communication.

**Comment by ptrdtznr** [comment]
The world “disposition” is typically used in the field of TransportManagementSystem related to trucks. Here, we should use the word “assignment” instead of using “disposition”. To manifest my, have a look at google scholar.
