### ISSUE TITLE
Refactor YAML scenariofile parser

### ISSUE THREAD

**Issue by ltoenning** [iml130/sola#34]
Currently most of the application specific parsing is done in the corresponding manager classes. Only a small common part is handled in the ``ScenariofileParser``. Further, we often require to parse a key-value/``std::map`` like structure from YAML and pass the extracted data to existing data classes, like:

https://github.com/iml130/sola/blob/a7c868562c959fb90b427d616caf3dd24531b264/daisi/src/cpps/common/cpps_manager.cpp#L733-L744

The objective of this issue is to simplify the parsing. One idea is to create separate classes for the different types of scenariofiles (for example ``CppsScenarioFile``) which implement parsing methods like the application message classes for serialization with Cereal.

**Comment by janagoe** [comment]
As you mentioned, there are many small classes "hidden" in the scenario file, such as

- `AmrKinematics`,
- `AmrDescription`, or
- `Topology`,

where delegating the parsing into the classes themselves could make the code a lot more modular. 

In addition, we created many implicit classes which get parsed by the manager, such as AMR or MaterialFlow spawning information like 
```
- amr1:
    type: "amr"
    friendly_name: "LR"
    start_time: 0
    distribution: abs
    abs: 3
```

For those, we could also create individual classes.

**Comment by janagoe** [comment]
Another problem we had in the past regarding the scenario file was writing execution and evaluation scripts. 

For execution, our python scripts had to generate the yaml files. And in evaluation, our python scripts had to read parts of the yaml files. 

This lead to basically rewriting all classes in python for a parsing and writing yaml files multiple times along different repositories. 

I would suggest implementing serialization (writing) and deserialization (parsing) methods for each scenario file related class. 

Then, if we start writing execution and evaluation scripts again, we could use a C++-Python wrapper.
This would enable reusing the C++ classes in our python scripts and we do not have to rewrite and update them in python  continuously each time the C++ code changes. 

A library such as `cppyy` could be useful. https://cppyy.readthedocs.io/en/latest/

**Comment by janagoe** [comment]
I'd love to have some base class for the scenario file related classes along the lines of
```
class ScenarioComponent {
public:
    static ScenarioComponent deserialize(std::string yaml_string) = 0; 
    std::string serialize(YAML::Node node) = 0;
};
```

and letting each core class derive from it such as 

```
class AmrDescriptionScenarioComponent : public AmrDescription, ScenarioComponent {
    ...
};

```
